## Activity 7.1

In [60]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import sklearn.metrics as metrics
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [61]:
df = pd.read_csv("C:/Users/Utilizador/Desktop/Bioinf/2º ano/2º semestre/AA/Naive-Bayes-master/Naive-Bayes-Classification-Data.csv")
df.head()

glucose  bloodpressure  diabetes
0       40             85         0
1       40             92         0
2       45             63         1
3       45             80         0
4       40             73         1

In [62]:
x = df.drop('diabetes', axis=1)
y = df['diabetes']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [63]:
model = GaussianNB()

# Fit Gaussian Naive Bayes according to X, y
model.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [64]:
# Get parameters for this estimator
model.get_params()

{'priors': None, 'var_smoothing': 1e-09}

In [65]:
# Incremental fit on a batch of samples
model.partial_fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [66]:
y_pred = model.predict(x_test)
y_test

920    1
525    1
567    1
657    0
633    0
      ..
490    1
707    0
894    0
208    0
277    0
Name: diabetes, Length: 249, dtype: int64

In [67]:
# Returns the log-probability of the samples for each class in the model
model.predict_log_proba(x_test)

array([[-5.94533695e+00, -2.62145307e-03],
       [-2.51990649e+00, -8.38894892e-02],
       [-9.59752906e+00, -6.78986024e-05],
       [-2.68276481e-03, -5.92224845e+00],
       [-1.16054799e-02, -4.46207501e+00],
       [-5.46488608e-02, -2.93402691e+00],
       [-2.51990649e+00, -8.38894892e-02],
       [-5.46488608e-02, -2.93402691e+00],
       [-2.51380636e-02, -3.69591480e+00],
       [-4.38780916e+00, -1.25057996e-02],
       [-9.52996012e-03, -4.65807594e+00],
       [-1.34217643e-01, -2.07465093e+00],
       [-2.68276481e-03, -5.92224845e+00],
       [-3.34663881e-01, -1.25729822e+00],
       [-2.68276481e-03, -5.92224845e+00],
       [-9.01027923e+00, -1.22155205e-04],
       [-1.15314100e+00, -3.79276700e-01],
       [-1.69862048e+01, -4.19744488e-08],
       [-3.79354921e+00, -2.27728926e-02],
       [-3.43840972e-03, -5.67446492e+00],
       [-8.55665327e-02, -2.50093926e+00],
       [-7.50442587e+00, -5.50793560e-04],
       [-9.40688928e+00, -8.21594898e-05],
       [-1.

In [68]:
# Returns the probability of the samples for each class in the model
model.predict_proba(x_test)

array([[2.61802007e-03, 9.97381980e-01],
       [8.04671312e-02, 9.19532869e-01],
       [6.78962974e-05, 9.99932104e-01],
       [9.97320831e-01, 2.67916942e-03],
       [9.88461604e-01, 1.15383961e-02],
       [9.46817554e-01, 5.31824457e-02],
       [8.04671312e-02, 9.19532869e-01],
       [9.46817554e-01, 5.31824457e-02],
       [9.75175266e-01, 2.48247335e-02],
       [1.24279270e-02, 9.87572073e-01],
       [9.90515306e-01, 9.48469395e-03],
       [8.74399737e-01, 1.25600263e-01],
       [9.97320831e-01, 2.67916942e-03],
       [7.15578565e-01, 2.84421435e-01],
       [9.97320831e-01, 2.67916942e-03],
       [1.22147744e-04, 9.99877852e-01],
       [3.15643775e-01, 6.84356225e-01],
       [4.19744470e-08, 9.99999958e-01],
       [2.25155475e-02, 9.77484453e-01],
       [9.96567495e-01, 3.43250516e-03],
       [9.17992064e-01, 8.20079355e-02],
       [5.50641901e-04, 9.99449358e-01],
       [8.21561148e-05, 9.99917844e-01],
       [9.88461604e-01, 1.15383961e-02],
       [9.825792

In [69]:
# Predict the response for the test datasets
y_pred = model.predict(x_test)

In [70]:
# Compute confusion matrix to evaluate the accuracy of a classification
print(metrics.confusion_matrix(y_test, y_pred))

[[105   9]
 [  9 126]]


In [71]:
accuracy = accuracy_score(y_test, y_pred)*100
accuracy

92.7710843373494