In [1]:
# imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Load file
dataset = pd.read_csv('C:/Users/ASUS/Documents/AA/Activity2/Iris.csv')

In [5]:
# Show all the lines on the file
dataset.head(150)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
14    15            5.8           4.0            1.2           0.2   
15    16            5.7           4.4            1.5           0.4   
16    17            5.4           3.9            1.3           0.4   
17    18            5.1           3.5            1.4           0.3   
18    19            5.7           3.8            1.7           0.3   
19    20            5.1           3.8            1.5           0.3   
20    21            5.4           3.4            1.7           0.2   
21    22            5.1           3.7            1.5           0.4   
22    23            4.6           3.6            1.0           0.2   
23    24            5.1           3.3            1.7           0.5   
24    25            4.8           3.4            1.9           0.2   
25    26            5.0           3.0            1.6           0.2   
26    27            5.0           3.4            1.6           0.4   
27    28            5.2           3.5            1.5           0.2   
28    29            5.2           3.4            1.4           0.2   
29    30            4.7           3.2            1.6           0.2   
30    31            4.8           3.1            1.6           0.2   
31    32            5.4           3.4            1.5           0.4   
32    33            5.2           4.1            1.5           0.1   
33    34            5.5           4.2            1.4           0.2   
34    35            4.9           3.1            1.5           0.1   
35    36            5.0           3.2            1.2           0.2   
36    37            5.5           3.5            1.3           0.2   
37    38            4.9           3.1            1.5           0.1   
38    39            4.4           3.0            1.3           0.2   
39    40            5.1           3.4            1.5           0.2   
40    41            5.0           3.5            1.3           0.3   
41    42            4.5           2.3            1.3           0.3   
42    43            4.4           3.2            1.3           0.2   
43    44            5.0           3.5            1.6           0.6   
44    45            5.1           3.8            1.9           0.4   
45    46            4.8           3.0            1.4           0.3   
46    47            5.1           3.8            1.6           0.2   
47    48            4.6           3.2            1.4           0.2   
48    49            5.3           3.7            1.5           0.2   
49    50            5.0           3.3            1.4           0.2   
50    51            7.0           3.2            4.7           1.4   
51    52            6.4           3.2            4.5           1.5   
52    53            6.9           3.1            4.9           1.5   
53    54            5.5           2.3            4.0           1.3   
54    55            6.5           2.8            4.6           1.5   
55    56            5.7           2.8            4.5           1.3   
56    57        

In [6]:
# label of the variables
dataset['Species'] = dataset['Species'].replace('Iris-setosa',0)
dataset['Species'] = dataset['Species'].replace('Iris-versicolor',1)
dataset['Species'] = dataset['Species'].replace('Iris-virginica',2)

In [7]:
# Prints the dataset
dataset

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
5      6            5.4           3.9            1.7           0.4        0
6      7            4.6           3.4            1.4           0.3        0
7      8            5.0           3.4            1.5           0.2        0
8      9            4.4           2.9            1.4           0.2        0
9     10            4.9           3.1            1.5           0.1        0
10    11            5.4           3.7            1.5           0.2        0
11    12            4.8           3.4            1.6           0.2        0
12    13            4.8           3.0            1.4           0.1        0
13    14            4.3           3.0            1.1           0.1        0
14    15            5.8           4.0            1.2           0.2        0
15    16            5.7           4.4            1.5           0.4        0
16    17            5.4           3.9            1.3           0.4        0
17    18            5.1           3.5            1.4           0.3        0
18    19            5.7           3.8            1.7           0.3        0
19    20            5.1           3.8            1.5           0.3        0
20    21            5.4           3.4            1.7           0.2        0
21    22            5.1           3.7            1.5           0.4        0
22    23            4.6           3.6            1.0           0.2        0
23    24            5.1           3.3            1.7           0.5        0
24    25            4.8           3.4            1.9           0.2        0
25    26            5.0           3.0            1.6           0.2        0
26    27            5.0           3.4            1.6           0.4        0
27    28            5.2           3.5            1.5           0.2        0
28    29            5.2           3.4            1.4           0.2        0
29    30            4.7           3.2            1.6           0.2        0
30    31            4.8           3.1            1.6           0.2        0
31    32            5.4           3.4            1.5           0.4        0
32    33            5.2           4.1            1.5           0.1        0
33    34            5.5           4.2            1.4           0.2        0
34    35            4.9           3.1            1.5           0.1        0
35    36            5.0           3.2            1.2           0.2        0
36    37            5.5           3.5            1.3           0.2        0
37    38            4.9           3.1            1.5           0.1        0
38    39            4.4           3.0            1.3           0.2        0
39    40            5.1           3.4            1.5           0.2        0
40    41            5.0           3.5            1.3           0.3        0
41    42            4.5           2.3            1.3           0.3        0
42    43            4.4           3.2            1.3           0.2        0
43    44            5.0           3.5            1.6           0.6        0
44    45            5.1           3.8            1.9           0.4        0
45    46            4.8           3.0            1.4           0.3        0
46    47            5.1           3.8            1.6           0.2        0
47    48            4.6           3.2            1.4           0.2        0
48    49            5.3           3.7            1.5           0.2        0
49    50            5.0           3.3            1.4           0.2        0
50    51            7.0           3.2            4.7           1.4        1
51    52            6.4           3.2            4.5  

In [8]:
# Lenght of the dataset
dataset.shape

(150, 6)

In [9]:
# Isolate the variable of interest 
x = dataset.drop('Species', axis=1)
y = dataset['Species']

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=101, shuffle= True, stratify=y)
# The test size is 30%, 
# The other parameters ensure that the algorithm doesn't focus just on one group

In [11]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)
# Adjust the model to the data 

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
predictions = logmodel.predict(x_test)
print('Predictions:\n', predictions)
# Make predictions

Predictions:
 [2 2 1 0 2 2 2 2 0 1 0 0 1 0 2 2 0 0 0 2 1 1 1 1 2 1 2 0 2 2 0 1 1 1 0 2 1
 1 0 2 0 0 1 0 1]


In [13]:
from sklearn.metrics import confusion_matrix
results = confusion_matrix(y_test, predictions)
print('Confusion Matrix:\n', results)
# Confusion Matrix

Confusion Matrix:
 [[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]


In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))
# The classification report visualizer displays the precision and support scores for the model.

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        15

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [16]:
from sklearn import metrics
print('Accuracy:\n', metrics.accuracy_score(y_test,predictions))
# Show how accurate is our prediction

Accuracy:
 1.0


In [17]:
# The accuracy of the prediction is "perfect" (100%) because there are the same number of data for each specie

In [18]:
# Bernardo Augusto 2814
# Catarina Canastra 2821